### PR TITLE
Support rgb/rgba and hsl/hsla colors in parameters, fixes #39

### LINKED ISSUE #39: rgb values cannot be passed as parameters
SVG:
```xml
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 10 8' enable-background='new 0 0 10 8' xml:space='preserve'><rect style="fill:var(--color,black)" width="100%" height="100%"/></svg>
```

CSS:
```css
.square::after {
    content: url("embed/Check.svg" param(--color rgb(1,1,1)));
}
```

Result:
```css
.square::after {
    content: url("data:image/svg+xml;charset=utf-8,%3Csvg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 10 8' enable-background='new 0 0 10 8' xml:space='preserve'%3E%3Crect style='fill:black' width='100%25' height='100%25'/%3E%3C/svg%3E");
}
```

However, if `blue` or `#FFF` is passed, everything works as expected.

I'll send a PR that fixes this shortly.

### PR DESCRIPTION
**Pull request by lazd**
### Changes

This PR adds support for rgb and hsl color values in parameters:

```
test-sprite-with-rgb-param {
	background-image: url("sprite-camera.svg" param(--color rgb(0, 0, 255)));
}

test-sprite-with-rgba-param {
	background-image: url("sprite-camera.svg" param(--color rgba(0, 0, 255, 0.5)));
}

test-sprite-with-hsl-param {
	background-image: url("sprite-camera.svg" param(--color hsl(240, 100%, 50%)));
}

test-sprite-with-hsla-param {
	background-image: url("sprite-camera.svg" param(--color hsla(240, 100%, 50%, 0.5)));
}
```

Tests are included, and the output has been tested in a live project.

`package.lock.json` has been committed as well.

### CODE REVIEW

**Comment by jonathantneal** [comment]
Looks good. Now I’m reviewing this to see what happens currently before the changes.

**Comment by lazd** [comment]
@jonathantneal thanks! Currently, `isFilledParam` returns `false` as the node type of the value is `function`, not `word`, so the default value gets substituted in (if provided). It does not error.

**Comment by jonathantneal** [comment]
@lazd, thanks for informing me of this bug, and going the extra awesome mile to make a PR for it.

I will accept the PR as is, but I would prefer a smaller change. If you’re okay with this, I’d prefer to work with you and let you make the change I’m suggesting.

The real bug appears to be that we should support non-`word` params. That can be done by removing the last type check in `isFilledParam` on L121:

```js
return node.type === 'function' && node.value === 'param' && node.nodes.length === 3 && node.nodes[0].type === 'word';
```

Then, because we’re still allowing the param value to be any value node, we should just stringify that node on L110:

```js
params[node.nodes[0].value] = parser.stringify(node.nodes[2]);
```

And that’s it! That should solve your problem, and still not limit us to the known color functions you were manually checking for. What do you think?

**Comment by jonathantneal** [comment]
Well, I can just amend your commit so you can still get credit :)

**Comment by lazd** [comment]
That sounds perfect, I'll go ahead and insolent that shortly. Thanks for the guidance!

**Comment by jonathantneal** [comment]
Released as 2.1.0!

**Comment by lazd** [comment]
@jonathantneal you're too fast, thanks!

**Pull request merged**
